import Contact from "./components/Contact/Contact";
import Navbar from "./components/Navbar/Navbar";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <head>
        <link rel='icon' href='/favicon.ico' />
      </head>

      <body>
        {/* <Navbar /> */}
        {children}
        {/* <Contact /> */}
      </body>
    </html>
  );
}
